openapi: "3.0.0"
info:
  version: 0.9.0
  title: Cloud Failover (CF) Extension
  description: F5 Cloud Failover (CF) is an iControl LX Extension delivered as a TMOS-independent RPM file. Installing the TS Extension on BIG-IP enables you to declaratively configure BIG-IP devices for automatic failover in cloud environments by POSTing a single JSON declaration to CFâ€™s declarative REST API endpoint.
  license:
    name: Apache License 2.0
servers:
  - url: https://192.0.2.1:443/mgmt/shared/cloud-failover
paths:
  /declare:
    get:
      summary: List configuration
      tags:
        - Configuration
      responses:
        "200":
          description: Configuration Response
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/ConfigurationResponse"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Update configuration
      tags:
        - Configuration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Configuration"
            example:
              class: Cloud_Failover
              environment: azure
              externalStorage:
                scopingTags:
                  F5_CLOUD_FAILOVER_LABEL: mydeployment
              failoverAddresses:
                scopingTags:
                  F5_CLOUD_FAILOVER_LABEL: mydeployment
              failoverRoutes:
                scopingTags:
                  F5_CLOUD_FAILOVER_LABEL: mydeployment
                scopingAddressRanges:
                  - "192.0.2.0/24"
      responses:
        "200":
          description: Configuration response
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/ConfigurationResponse"
              example:
                message: success
                declaration:
                  class: Cloud_Failover
                  environment: azure
                  schemaVersion: "0.9.0"
                  externalStorage:
                    scopingTags:
                      F5_CLOUD_FAILOVER_LABEL: mydeployment
                  failoverAddresses:
                    scopingTags:
                      F5_CLOUD_FAILOVER_LABEL: mydeployment
                  failoverRoutes:
                    scopingTags:
                      F5_CLOUD_FAILOVER_LABEL: mydeployment
                    scopingAddressRanges:
                      - "192.0.2.0/24"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /trigger:
    post:
      summary: Trigger failover
      tags:
        - Trigger
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
            example:
              action: execute
      responses:
        "200":
          description: Configuration response
          content:
            "application/json; charset=UTF-8":
              schema:
                type: object
                properties:
                  taskState:
                    type: string
              example:
                message: in_progress
    get:
      summary: Running failover task state
      tags:
        - Trigger
      responses:
        "202":
          description: Failover task is running
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/ConfigurationResponse"
        "200":
          description: Failover task was successful
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/ConfigurationResponse"
        "400":
          description: Failover task failed
          content:
            "application/json; charset=UTF-8":
              schema:
                $ref: "#/components/schemas/ConfigurationResponse"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Configuration:
      type: object
      properties:
        class:
          type: string
          default: "Cloud_Failover"
        environment:
          type: string
          enum:
            - azure
            - aws
            - gcp
        schemaVersion:
          type: string
        externalStorage:
          type: object
          properties:
            scopingTags:
              type: object
              additionalProperties: true
        failoverAddresses:
          type: object
          properties:
            scopingTags:
              type: object
              additionalProperties: true
        failoverRoutes:
          type: object
          properties:
            scopingTags:
              type: object
              additionalProperties: true
            scopingAddressRanges:
              type: array
    ConfigurationResponse:
      type: object
      properties:
        message:
          type: string
        declaration:
          type: object
          $ref: "#/components/schemas/Configuration"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
